version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ~/.config/:/root/.config
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DB_URL: <DB_URL>
      ENV: prod
